logging:
  pattern:
    console: "%level %msg%n"

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      timeout: 30_000
      chat:
        options:
          model: gpt-5-mini
          temperature: 1
